TPModule6/Controllers/SamouraisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BO;
using TPModule6.Data;
using TPModule6.Models;

namespace TPModule6.Controllers
{
    public class SamouraisController : Controller
    {
        private TPModule6Context db = new TPModule6Context();

        // GET: Samourais
        public ActionResult Index()
        {
            return View(db.Samourais.ToList());
        }

        // GET: Samourais/Details/5
        public ActionResult Details(int? id)
        {

            DojoViewModel dvm = new DojoViewModel();
            dvm.samourai = db.Samourais.FirstOrDefault(x => x.Id == id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Samourai samourai = db.Samourais.Find(id);
            if (samourai == null)
            {
                return HttpNotFound();
            }
            return View(dvm);
        }

        // GET: Samourais/Create
        public ActionResult Create()
        {
            //créer liste arme et la retourner

            DojoViewModel dvm = new DojoViewModel();
            dvm.Armes = db.Armes.Select(x => new SelectListItem() { Text = x.Nom, Value = x.Id.ToString() }).ToList();

            return View(dvm);
        }

        // POST: Samourais/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DojoViewModel dvm)
        {
            if (ModelState.IsValid)
            {
                //récupérer, rattaché l'armeId au samourai
                Samourai samourai = dvm.samourai;
                samourai.Arme = db.Armes.Find(dvm.IdArmes);
                db.Samourais.Add(samourai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dvm);
        }

        // GET: Samourais/Edit/5
        public ActionResult Edit(int? id)
        {
            DojoViewModel dvm = new DojoViewModel();
            dvm.Armes = db.Armes.Select(x => new SelectListItem() { Text = x.Nom, Value = x.Id.ToString() }).ToList(); // retourne la liste complète d'armes

            dvm.samourai = db.Samourais.Find(id);
            dvm.IdArmes = dvm.samourai.Arme.Id;   // récupère et affiche l'arme sélectionnée

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dvm.samourai == null)
            {
                return HttpNotFound();
            }
            return View(dvm);
        }

        // POST: Samourais/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Samourai samourai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(samourai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(samourai);
        }

        // GET: Samourais/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Samourai samourai = db.Samourais.Find(id);
            if (samourai == null)
            {
                return HttpNotFound();
            }
            return View(samourai);
        }

        // POST: Samourais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Samourai samourai = db.Samourais.Find(id);
            db.Samourais.Remove(samourai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TPModule6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Armes", "Index", "Armes")</li>
                    <li>@Html.ActionLink("Samouraïs", "Index", "Samourais")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TPModule6/Views/Shared/_SamouraiDisplay.cshtml
@model TPModule6.Models.DojoViewModel


<h4>Samourai</h4>
<hr />

<div class="form-group">
    @Html.LabelFor(model => model.samourai.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.samourai.Nom, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.samourai.Nom, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.samourai.Force, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.samourai.Force, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.samourai.Force, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Armes, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @if (Model.Armes != null && Model.Armes.Count > 0)
        {
            @Html.DropDownListFor(model => model.IdArmes, Model.Armes,"Sélectionner une arme", new { htmlAttributes = new { @class = "form-control" } })
        }
        else
        {
            @Html.DisplayFor(model => model.samourai.Arme.Nom)
        }


        @Html.ValidationMessageFor(model => model.Armes, "", new { @class = "text-danger" })

    </div>
</div>

TPModule6/Views/Shared/_SamouraiDisplayWithId.cshtml
@model TPModule6.Models.DojoViewModel


@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.HiddenFor(model => model.samourai.Id) <!--Permet de récupérer le samourai sélectionné-->

@Html.Partial("_SamouraiDisplay")